### ISSUE TITLE
Cannot reject a war

### ISSUE THREAD

**Issue by bricebrosig** [AlecSweet/DiscordPointBot#7]
Cannot reject a war when offered from another user.
![image](https://github.com/AlecSweet/DiscordPointBot/assets/32393924/3cb36c8e-7316-4768-9736-55930fd66ab6)

The cancel button is presented, but does nothing if you did not start the war.
![image](https://github.com/AlecSweet/DiscordPointBot/assets/32393924/db06ffaf-c391-4cc0-aed0-d8e9aedc1e61)

Request:
If someone offers a war, the offeree should be able to reject it explicitly.

**Comment by AlecSweet** [comment]
might
